# Generated by Django 5.0.1 on 2024-01-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_request_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_request_app.requisite')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
